#!/usr/bin/env python
"""
This file is part of the py-boinc-plotter,
which provides parsing and plotting of boinc statistics and
badge information.
Copyright (C) 2013 obtitus@gmail.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
# END LICENCE
# This file is autogenerated by setup.py, do not edit.
__version_info__ = (0, 2, 4)
__version__ = "0.2.4"
appName = "pyBoincPlotter"
appAuthor = "obtitus"
